package com.olgefilimonov.gifer.domain.entity;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

/**
 * @author Oleg Filimonov
 */
@Entity
public class RatedGifEntity {
  @Id private long id;
  private String gifId;
  private int score;

  public RatedGifEntity() {
  }

  @Generated(1851863774)
  @Internal
  /** This constructor was generated by ObjectBox and may change any time. */ public RatedGifEntity(
      long id, String gifId, int score) {
    this.id = id;
    this.gifId = gifId;
    this.score = score;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getGifId() {
    return gifId;
  }

  public void setGifId(String gifId) {
    this.gifId = gifId;
  }

  public int getScore() {
    return score;
  }

  public void setScore(int score) {
    this.score = score;
  }
}
